# Generated by Django 4.2.13 on 2024-07-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
