# Generated by Django 4.2.13 on 2024-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='date',
            field=models.DateField(default='2018-07-11'),
            preserve_default=False,
        ),
    ]
