# Generated by Django 4.2.13 on 2024-05-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
